apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: registry-authentik
  namespace: authentik
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ `{{ .CONTENT  `}} }}"
    name: registry-authentik
  data:
  - secretKey: CONTENT
    remoteRef:
      key: container-registry/dockerconfig.json
      property: CONTENT