apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-postgres
  namespace: authentik
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    template:
      type: opaque
      data:
        host: "{{ `{{ .HOST_CONTENT  `}} }}"
        username: "{{ `{{ .USERNAME_CONTENT  `}} }}"
        password: "{{ `{{ .PASSWORD_CONTENT  `}} }}"
    name: authentik-postgres
  data:
  - secretKey: HOST_CONTENT
    remoteRef:
      key: authentik/database
      property: POSTGRES_HOST
  - secretKey: USERNAME_CONTENT
    remoteRef:
      key: authentik/database
      property: POSTGRES_USER
  - secretKey: PASSWORD_CONTENT
    remoteRef:
      key: authentik/database
      property: POSTGRES_PASSWORD