apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-admin
  namespace: authentik
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: authentik-admin
  data:
  - secretKey: AUTHENTIK_BOOTSTRAP_PASSWORD 
    remoteRef: 
      key: authentik/admin
      property: AUTHENTIK_BOOTSTRAP_PASSWORD
  - secretKey: AUTHENTIK_BOOTSTRAP_EMAIL
    remoteRef: 
      key: authentik/admin
      property: AUTHENTIK_BOOTSTRAP_EMAIL
  - secretKey: AUTHENTIK_BOOTSTRAP_TOKEN
    remoteRef: 
      key: authentik/admin
      property: AUTHENTIK_BOOTSTRAP_TOKEN
  - secretKey: AUTHENTIK_SECRET_KEY
    remoteRef: 
      key: authentik/admin
      property: AUTHENTIK_SECRET_KEY